language: node_js
node_js: node
services: 
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: Lg1TF2hDIlG26Vq4pr3jfNkz/iH4H4QP/4rrHT1lmrVWBukwFHNutneIW1a74Knwtriq78lIH9bWkzQHYzfydA1Tx7sSUkDONQWVxv1B2DwwcuvGMIPgp1SQXLeI4Coa4aDFNgUUCHZpahd+CNFSxFhD6lVvTncKvcepe2+MyVwrXUYxy1Q8kTOjYPr5egsbgmNSG/5OKf2nRU6RsPtuvPIW6Qbs2VgvweCtfQBwI/itrZ2UMmkng1Fx21s7tPkHWd0dbOYbxWKnmyT1JneW8F3sk2u9BqgkQsCDnhqU6No8vjoglLH7m/X/cm88+iJ8fZs/9S2NdONoZQnWdq846wNfE4V6h/hqLYlb0VfaGhy5nDHPBPddLclkI1kdCwhOsvgvgbsiBszUJ2Z9pOwpVi4QOSxVyMR6DChUp3obqWfPPbE4zNC0wms9seqdhx+wtvWcno4aP+6SqNl/SIycFPDHhE6XlT/tdEcK2QKXKSXwKw+7mjSpw8m55pGO1wWsjazr1WhujzJg2zrn0ffJUx6HwmbjE0VFGD/ZaPR6yGmnHKcFIX0tsCCzW9VYJuVJRvUf6ENy4//vopo/jEtlS5ltfTYODrFY8+nFdAKp2tsLuohzHYgtECMJcRjeHbpNZc2La8aa9Kw5+EeV77KjaEIQAajqe+h8dln9MYaoXM8=
  app: take-one-leave-one
  on:
    repo: strewburry/TOLO
